### ISSUE TITLE
Can't install node module on MacOs Catalina due to node-gyp@3.8.0

### ISSUE THREAD

**Issue by phamhieu** [pyramation/libpg-query-node#5]
I can't install this package on MacOs Catalina. Can you pump up the version for node-gyp. The current one is too old.

```
// node-gyp@3.8.0 released 3 years ago
"node-gyp": "^3.3.1"
```

[[ERROR] TypeError: cannot use a string pattern on a bytes-like object](https://github.com/nodejs/node-gyp/issues/2121)

```bash
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@12.18.4 | darwin | x64
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/.../node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/.../node_modules/libpg-query/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/.../node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/phamhieu/.node-gyp/12.18.4/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/phamhieu/.node-gyp/12.18.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/.../node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/phamhieu/.node-gyp/12.18.4/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/.../node_modules/libpg-query',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "./gyp-mac-tool", line 611, in <module>
npm ERR!     sys.exit(main(sys.argv[1:]))
npm ERR!   File "./gyp-mac-tool", line 28, in main
npm ERR!     exit_code = executor.Dispatch(args)
npm ERR!   File "./gyp-mac-tool", line 43, in Dispatch
npm ERR!     return getattr(self, method)(*args[1:])
npm ERR!   File "./gyp-mac-tool", line 246, in ExecFilterLibtool
npm ERR!     if not libtool_re.match(line) and not libtool_re5.match(line):
npm ERR! TypeError: cannot use a string pattern on a bytes-like object
npm ERR! make: *** [Release/nothing.a] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/.../node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/.../node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/.../node_modules/libpg-query
npm ERR! gyp ERR! node -v v12.18.4
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
```

**Comment by pyramation** [comment]
@phamhieu can you test libpg-query@13.1.0?

If it works, I'll merge this PR: https://github.com/pyramation/libpg-query-node/pull/6

**Comment by phamhieu** [comment]
Yay! it works. 

I got this problem while installing `pgsql-parser`. Could you update that package to support this version please. Thank you @pyramation.

```bash
(base) app % npm i libpg-query@13.1.0

added 53 packages, and audited 1566 packages in 1m

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(base) app % 
```

**Comment by pyramation** [comment]
yay merged and also upgraded `pgsql-parser`

try pgsql-parser@13.1.3

Thanks for the note @phamhieu - if everything works let me know and I'll close this out, cheers!

**Comment by phamhieu** [comment]
> try pgsql-parser@13.1.3

Yes, it works properly now. Thanks @pyramation

**Comment by pyramation** [comment]
sounds good 🚀
